### ISSUE TITLE
"Cannot set property once" error when used with zone.js

### ISSUE THREAD

**Issue by vigie** [webcomponents/polyfills#531]
### Description

When used with zone.js (all Angular applications), following error is thrown:

```
zone.js:1953 Uncaught TypeError: Cannot set property once of [object Object] which has only a getter
    at HTMLDivElement.addEventListener (zone.js:1953:42)
    at webcomponents-bundle.js:98:596
    at webcomponents-bundle.js:98:767
    at webcomponents-bundle.js:382:176
```

### Steps to reproduce

Generate an Angular app and include this polyfill. Start the app.

#### Expected behavior

Should not throw error

#### Actual behavior

Above error is thrown

### Version

This was introduced in version 2.7 by this PR https://github.com/webcomponents/polyfills/pull/469

### Browsers affected

Only tested on Chrome

**Comment by mohit-sahore** [comment]
I am facing the same issue for the last 5 days. Any update on this?

**Comment by inspector-code** [comment]
The same problem. Are there any solutions?

**Comment by tappmax** [comment]
I have the same issue. Is this the problem here? https://github.com/webcomponents/polyfills/blob/master/packages/webcomponentsjs/ts_src/platform/event-listener-options.ts#L26

**Comment by tappmax** [comment]
Unfortunately, my current solution to this is to use the previous minor version.

**Comment by marlberm2014** [comment]
@tappmax downgrading to 2.6 also works for me. Hopefully this is fix in the next releases.

**Comment by mme-private** [comment]
Can confirm, problem is still actual.

**Comment by Volftsun** [comment]
Same here, the bug still actual
